#pragma once

// Convenience single-include header for BerkEngine ECS
#include "Types.h"
#include "EntityManager.h"
#include "ComponentArray.h"
#include "ComponentManager.h"
#include "System.h"
#include "SystemManager.h"
#include "World.h"
#include "Event.h"
#include "EventQueue.h"
#include "Platform.h"
#include "SDLPlatform.h"
#include "Timer.h"
#include "Asset.h"
#include "AssetManager.h"
#include "Renderer.h"
#include "HeadlessRenderer.h"
#include "Scene.h"
#include "Application.h"
#include "Engine.h"
